/** Presenter notes. N toggles. Running clock is for a 22-minute slot. */
export const NOTES: readonly string[] = [
  "0:00. Open with xAI's line: nothing to learn, it is like bringing on a coworker. Then say what tonight is: what that coworker is allowed to do, and where it has to stop. Skip the launch film unless the room is cold.",
  "0:45. Click around for a minute. The room first, then Chief of Staff, then the computer icon, then its settings. Say the one sentence that matters: a sidebar of Bots, one chat each, and a computer behind every Bot. That is all there is to the app.",
  "1:45. Promise what they leave with. A Bot with a real job, and a rule about when it asks. Say the five verbs out loud: send, publish, buy, delete, sign. You will use the same five all night.",
  "2:30. Hands up. Inbox Manager, Expense Manager or Sales Outbound. Do not scroll the rest of the catalogue. If the room stalls, pick Inbox Manager, everyone has one.",
  "3:30. Five words, quickly. Point at Prompt: use it once, save it as a Skill, schedule it as a Routine. Everything else on this list you already saw in the app two slides ago.",
  "4:30. Live: create Chief of Staff. Read the description out as you type a shorter version of it. Then create the specialist the room picked. Two Bots, no more. Say the small print: this creates the Bot. Plugins and the approval rule come next, and they are the next two slides.",
  "6:30. Live: open Plugins, add one (X first, pstack as backup). Say it plainly: a plugin belongs to the account. Then in a Bot's settings you tell it which ones to use. That is an instruction, not a lock. Every Bot can still reach all of them.",
  "8:00. Live: open Settings and show Require approval. Read the five verbs. Then say the rule for tonight: you are not done setting up until you have watched the Bot stop once. You will force that stop after the first task.",
  "9:30. If a login comes up during the demo, do the takeover slowly enough for the back row to see the banner. Type the code yourself. Hand control back. If no login comes up, say the three levels and move on.",
  "11:00. Put the five parts on the projector. Say what each one asks. Then go to the next slide and read the filled-in version for the job the room picked.",
  "12:00. Click the tab for the job the room picked and read it. Type it into Chief's chat live, or paste it. Do not ad-lib a longer version. The Bot does what you describe.",
  "14:00. While the Bot works, show what the first result should look like: a list and drafts, never a send. Then force the stop: ask the specialist to send one of its drafts, and show the card. If the live result is slower than the slide, talk over this slide and come back.",
  "16:00. Now the part underneath. Close the laptop, the Bot keeps working. The computer is the Bot's, so your laptop has nothing to do with whether the job finishes.",
  "17:00. Hands up for more than one Slack. Most people here have three or four inboxes and several workspaces. Most agents assume one Gmail and one Slack. A Bot's computer can be signed into all of them at once.",
  "17:45. One computer, one desk per Bot, one set of logins. Handoffs are free because logins are shared. Say the consequence clearly: a second Bot adds no safety. When you told the Bot which plugins to use on slide 7, that was an instruction. It can still reach everything.",
  "18:45. Chat scrolls away. A file the Bot rereads does not. Rules that last go in the description. Facts that change go in a file. That is the whole memory model a beginner needs.",
  "19:30. Start with two Bots, not five. Duplicate work, two Bots on one file, updates nobody asked for. Two weeks of cleanup. Add a Bot when there is a whole job for it. Debbie's thumbnails stayed with the video editor.",
  "20:30. Read the three steps. Say that step three is the test: if the Bot did not stop, fix Settings before you give it anything else. Leave this slide up for questions, with x.ai/bot said out loud. Then hand over. This was the 101. The next fifteen minutes are how far the same app stretches.",
  "Appendix, only if asked. ChatGPT Projects: a chat with files. OpenClaw: you host and maintain it. Hermes: plain files on a machine you run. Grok Bot runs the machine for you. Self-hosted tools and Grok Bot can coexist. Say the date on the slide. This ages fast.",
];
